# Numpy
Numpy is the library in python programming language for scientific computation. It supports multi-dimensional array and matrices with the help of high-level mathematical functions which are written in this library. It is a scientific computation package written in python and contains many things like :
- Powerful N-dimensional array object.
- Broadcasting functions.
- Tools for integrating C/C++ and Fortran code.
- Useful for computing linear algebra, Fourier transform, and random number capabilities.

Numpy is a python extension to add support for large , multi-dimensional arrays and matrices, along with a library of high-level mathematical function
- Topics
     - numpy arrays
       - double dimension arrays
       - resizing ,reshaping
       - vector multiplication
       - boolean filtering
       - querying using where()function
       - indexing
       - slicing
       - mean,median, standarddeviation,average
       - Transpose
       - broadcasting
     - numpy matrix
       - addition , Multiplication
       - Transpose , Inverse
     - numpy random module

In [18]:
x = 20

In [19]:
import sys

In [20]:
sys.getsizeof(x)

28

In [21]:
l = [2,3,4,5]
print(l)

[2, 3, 4, 5]


In [26]:
l[2]

4

In [27]:
sys.getsizeof(l)

104

In [22]:
from array import array

In [25]:
a = array('h',[43,43,23,34])
a

array('h', [43, 43, 23, 34])

In [28]:
a[2]

23

In [30]:
a[-3]

43

In [37]:
a[1:3]

array('h', [43, 23])

In [2]:
import numpy as np

In [46]:
a = np.array([2,4,678])

In [50]:
a.shape

(3,)

In [51]:
a[2]

678

In [54]:
a.dtype

dtype('int64')

In [56]:
a.max()

678

In [57]:
a.ndim

1

In [58]:
a.size

3

In [ ]:
a.nbytes


In [62]:
a = np.array(range(10))
print(a)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
int64


In [63]:
a = np.array(range(6), dtype = float)
print(a)

[0. 1. 2. 3. 4. 5.]


In [103]:
import numpy as np 
a = np.array(range(10), dtype = 'uint64')
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint64)

In [116]:
x= np.array([[1, 2, 3], [4, 5, 6]], np.int32)
print(type(x))

print(x.shape)

<class 'numpy.ndarray'>
(2, 3)


- Data Types

Bool ,  inti , int8,  int32,  int64,  int8,  uint8,  uint16,  uint32,  uint64,  float16,  float32,  floa64,  complex64,  complex128 ,  SNstring with n chars

In [117]:
a = np.arange(1,11,3,dtype = 'uint32')

In [118]:
a

array([ 1,  4,  7, 10], dtype=uint32)

In [120]:
a = np.empty(4)
print(a.dtype)
print(a)

float64
[2.14027765e+161 5.30276956e+180 3.31033942e-033 6.98476053e-076]


In [121]:
a = np.empty((4,3,2))
print(a.dtype)

float64


In [122]:
a = np.empty((4,3,2))
print(a.dtype)
print(a)

float64
[[[6.89838464e-310 4.68543317e-310]
  [6.89838483e-310 6.89838483e-310]
  [6.89837959e-310 6.89838484e-310]]

 [[6.89838485e-310 6.89837959e-310]
  [6.89837959e-310 6.89838287e-310]
  [6.89837959e-310 4.68543128e-310]]

 [[6.89838483e-310 6.89838483e-310]
  [6.89838481e-310 6.89838373e-310]
  [6.89837959e-310 6.89838226e-310]]

 [[6.89837959e-310 6.89838483e-310]
  [6.89838481e-310 6.89837959e-310]
  [6.89837959e-310 6.89838234e-310]]]


In [123]:
a = np.zeros((3,5),dtype='uint64')
print(a.dtype)
print(a)

uint64
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [124]:
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [125]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [144]:
a = np.arange(1,25,2)

In [145]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [146]:
a.reshape(2,3,2)

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11]],

       [[13, 15],
        [17, 19],
        [21, 23]]])

In [148]:
a.reshape(2,6)

array([[ 1,  3,  5,  7,  9, 11],
       [13, 15, 17, 19, 21, 23]])

In [149]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [154]:
a=np.resize(4,   6)
a

array([4, 4, 4, 4, 4, 4])

In [157]:
a=np.array([[0,1],[2,3]])
np.resize(a,(2,3))


array([[0, 1, 2],
       [3, 0, 1]])

In [156]:
np.resize(a,(1,4))

array([[0, 1, 2, 3]])

In [140]:
a=np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
import numpy as np
a = np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [160]:
a=np.arange(24)

In [161]:
a.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [163]:
a.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [164]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [165]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [171]:
a.resize(a.size)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [172]:
b = a.ravel()
print(b)
c = a.flatten()
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [174]:
for x in a:
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [175]:
for x in a.ravel():
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


- note

the diff is that flatten always returns a copy and ravel returns a view of the original array whenever possible

In [176]:
l =[[8,4,2],[1,5,7],[2,4,5]]
np.array(l)

array([[8, 4, 2],
       [1, 5, 7],
       [2, 4, 5]])

In [178]:
l =[(8,4,2),(1,5,7),(2,4,5)]
np.array(l)

array([[8, 4, 2],
       [1, 5, 7],
       [2, 4, 5]])

In [184]:
l[-1]

(2, 4, 5)

In [191]:
l[1],[2]

((1, 5, 7), [2])

In [195]:
l[::3]

[(8, 4, 2)]

In [196]:
l[:-1]

[(8, 4, 2), (1, 5, 7)]

In [198]:
print(l[2][1])

4

In [199]:
print(l[0]*2)

(8, 4, 2, 8, 4, 2)


In [206]:
l[1]=999 #append
l

[(8, 4, 2), 999, (2, 4, 5)]

In [208]:
l

[(8, 4, 2), 999, (2, 4, 5)]

In [3]:
a = np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
a = np.arange(1,25).reshape(4,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [5]:
a[1,:4] = 999
print(a)

[[  1   2   3   4   5   6]
 [999 999 999 999  11  12]
 [ 13  14  15  16  17  18]
 [ 19  20  21  22  23  24]]


In [9]:
a[3,:-1] = 999
print(a)

[[999 999 999 999   5   6]
 [999 999 999 999  11  12]
 [999 999 999 999 999  18]
 [999 999 999 999 999  24]]


In [11]:
a[1,:4] = 1234
a

array([[ 999,  999,  999,  999,    5,    6],
       [1234, 1234, 1234, 1234,   11,   12],
       [ 999,  999,  999,  999,  999,   18],
       [ 999,  999,  999,  999,  999,   24]])

In [22]:
a[2,:6]= '987654'
a

array([[   999,    999,    999,    999,      5,      6],
       [  1234,   1234,   1234,   1234,     11,     12],
       [987654, 987654, 987654, 987654, 987654, 987654],
       [   999,    999,    999,    999,    999,     24]])

In [23]:
a[1,:4] = a[3,:4]
a

array([[   999,    999,    999,    999,      5,      6],
       [   999,    999,    999,    999,     11,     12],
       [987654, 987654, 987654, 987654, 987654, 987654],
       [   999,    999,    999,    999,    999,     24]])

In [24]:
c = np.sin(a)# Python number method sin() returns the sine of x, in radians.
c

array([[-0.02646075, -0.02646075, -0.02646075, -0.02646075, -0.95892427,
        -0.2794155 ],
       [-0.02646075, -0.02646075, -0.02646075, -0.02646075, -0.99999021,
        -0.53657292],
       [ 0.10138992,  0.10138992,  0.10138992,  0.10138992,  0.10138992,
         0.10138992],
       [-0.02646075, -0.02646075, -0.02646075, -0.02646075, -0.02646075,
        -0.90557836]])

In [25]:
c


array([[-0.02646075, -0.02646075, -0.02646075, -0.02646075, -0.95892427,
        -0.2794155 ],
       [-0.02646075, -0.02646075, -0.02646075, -0.02646075, -0.99999021,
        -0.53657292],
       [ 0.10138992,  0.10138992,  0.10138992,  0.10138992,  0.10138992,
         0.10138992],
       [-0.02646075, -0.02646075, -0.02646075, -0.02646075, -0.02646075,
        -0.90557836]])

In [29]:
b = c>0
b

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False]])

In [28]:
c[b]

array([-0.02646075, -0.02646075, -0.02646075, -0.02646075, -0.95892427,
       -0.2794155 , -0.02646075, -0.02646075, -0.02646075, -0.02646075,
       -0.99999021, -0.53657292, -0.02646075, -0.02646075, -0.02646075,
       -0.02646075, -0.02646075, -0.90557836])

In [30]:
c[c<0]

array([-0.02646075, -0.02646075, -0.02646075, -0.02646075, -0.95892427,
       -0.2794155 , -0.02646075, -0.02646075, -0.02646075, -0.02646075,
       -0.99999021, -0.53657292, -0.02646075, -0.02646075, -0.02646075,
       -0.02646075, -0.02646075, -0.90557836])

In [32]:
c[c<0] = 0
c

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.10138992, 0.10138992, 0.10138992, 0.10138992, 0.10138992,
        0.10138992],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [33]:
c[(c<0) | (c >0.9)] = 0
c

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.10138992, 0.10138992, 0.10138992, 0.10138992, 0.10138992,
        0.10138992],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [37]:
c = np.arange(1,25).reshape(4,6)
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [39]:
np.where(c>17)

(array([2, 3, 3, 3, 3, 3, 3]), array([5, 0, 1, 2, 3, 4, 5]))

In [40]:
np.argmax(c)

23

In [41]:
np.argmin(c)

0

In [45]:
np.all(c)

True

In [48]:
x,y = np.where(c>17)
zip(x,y)

In [49]:
x = np.arange(1,13).reshape(3,4)
y = np.arange(13,25).reshape(3,4)

In [50]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
y

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [52]:
b = x%2==0

In [53]:
x[b]=y[b]

In [54]:
x

array([[ 1, 14,  3, 16],
       [ 5, 18,  7, 20],
       [ 9, 22, 11, 24]])

In [57]:
l = x%2==0

In [58]:
l

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [59]:
x *-1

array([[ -1, -14,  -3, -16],
       [ -5, -18,  -7, -20],
       [ -9, -22, -11, -24]])

In [66]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)

In [68]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [69]:
a+b

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [70]:
a*b

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [73]:
a/b

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ],
       [0.4375    , 0.47058824, 0.5       ]])

In [75]:
a.dot(b)
#numpy.dot(vector_a, vector_b, out = None) returns the dot product of vectors a and b.
# It can handle 2D arrays but considering them as matrix and will perform matrix multiplication

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [76]:
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [77]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [79]:
a.std()

2.581988897471611

In [80]:
a.var()

6.666666666666667

In [81]:
a.mean()

5.0

In [86]:
np.average(a)

5.0

In [88]:
a.all()

True

In [89]:
a.any()

True

In [92]:
print("--------------a_____--__---")
print(a)
print("--------------b_____--__---")
print(b)

--------------a_____--__---
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------b_____--__---
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [97]:
c = np.vstack((a,b))

In [98]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [100]:
a = np.mat('4 3 1; 2 1 8; 6 5 4')
b = np.mat([[2,5,6],[2,1,5],[7,8,9]])
c = np.mat(np.arange(9).reshape(3,3))
print(a)

[[4 3 1]
 [2 1 8]
 [6 5 4]]


In [101]:
b

matrix([[2, 5, 6],
        [2, 1, 5],
        [7, 8, 9]])

In [102]:
c

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [106]:
b.I

matrix([[-0.4025974 ,  0.03896104,  0.24675325],
        [ 0.22077922, -0.31168831,  0.02597403],
        [ 0.11688312,  0.24675325, -0.1038961 ]])

In [107]:
b.T

matrix([[2, 2, 7],
        [5, 1, 8],
        [6, 5, 9]])

In [108]:
a+b

matrix([[ 6,  8,  7],
        [ 4,  2, 13],
        [13, 13, 13]])

In [109]:
a*b

matrix([[21, 31, 48],
        [62, 75, 89],
        [50, 67, 97]])

In [110]:
np.random.rand(10)

array([0.39136015, 0.27971895, 0.9568813 , 0.18021729, 0.66818907,
       0.42567717, 0.80634551, 0.43028515, 0.3843149 , 0.08488754])

In [111]:
np.random.randint(1,101,size=10)

array([33, 28, 10, 81, 96, 61, 36,  3, 37, 65])

In [118]:
np.random.randint(1,11,size=20)

array([ 7,  3, 10,  4,  6,  7,  8,  7,  6,  6,  1,  8,  4,  9,  1,  4,  7,
        4,  3,  4])

In [123]:

from random import randint
print(randint(0,9),randint(0,9),randint(0,9),randint(0,9),)

6 1 8 4


In [124]:
np.random.sample((3,4))

array([[0.29775447, 0.85549822, 0.5062132 , 0.15037197],
       [0.19781696, 0.52434189, 0.27857139, 0.89980817],
       [0.59779207, 0.1816598 , 0.62956875, 0.23200611]])

In [125]:
np.random.random_sample((3,4))

array([[0.88608836, 0.45907902, 0.13967899, 0.0631421 ],
       [0.08840764, 0.16869423, 0.98004999, 0.14205719],
       [0.82495859, 0.43177151, 0.80657791, 0.88236335]])

In [126]:
c = np.random.random_sample((3,4))
l = c.tolist()
print(l)

[[0.459929312535033, 0.49425015689449114, 0.5139000086539812, 0.01978741198019751], [0.9326844464835332, 0.09403268478645421, 0.6582660213826516, 0.8926135314387184], [0.4391567936032277, 0.5482291547559776, 0.7157314346664977, 0.43260331226204585]]


In [128]:
c.shape

(3, 4)

In [130]:
import numpy as np
c = np.array([[0,1,2],
            [2,4,5],
            [6,2,1]])
c

array([[0, 1, 2],
       [2, 4, 5],
       [6, 2, 1]])

In [131]:
c *[5,3,1]

array([[ 0,  3,  2],
       [10, 12,  5],
       [30,  6,  1]])

In [132]:
c

array([[0, 1, 2],
       [2, 4, 5],
       [6, 2, 1]])

In [133]:
c * [[5],[3],[1]]

array([[ 0,  5, 10],
       [ 6, 12, 15],
       [ 6,  2,  1]])

# Broadcasting rules

in order for an operation to broadcast, the size of all the trailing dimensions for both arrays must either :
be equal OR one of them must be one

In [136]:
A(1d array):3
    
B(2d array):2x3

SyntaxError: invalid syntax (<ipython-input-136-17dd39dcbda7>, line 1)

### np.linspace(): 
devides the range into n equal partitions and returns list of points

In [137]:
np.linspace(1,100,15)

array([  1.        ,   8.07142857,  15.14285714,  22.21428571,
        29.28571429,  36.35714286,  43.42857143,  50.5       ,
        57.57142857,  64.64285714,  71.71428571,  78.78571429,
        85.85714286,  92.92857143, 100.        ])